version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_assistant
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
volumes:
  mysqldata:    
